server:
  port: 8080

eureka:
  client:
    serviceUrl:
      #defaultZone: http://ms-eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka
      
spring: 
  cloud:
    gateway:
      routes:
        - id: ms-authentication
          uri: lb://ms-authentication
          predicates:
            - Path=/api/v1/auth/**  
            
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/api/v1/customers/**  
            
        - id: ms-accounts
          uri: lb://ms-accounts
          predicates:
            - Path=/api/v1/accounts/**

        - id: ms-credits
          uri: lb://ms-credits
          predicates:
            - Path=/api/v1/credits/** 
            
        - id: ms-transactions
          uri: lb://ms-transactions
          predicates:
            - Path=/api/v1/transactions/**

        - id: ms-yanki
          uri: lb://ms-yanki
          predicates:
            - Path=/api/v1/yanki/**
            
        - id: ms-bootcoin
          uri: lb://ms-bootcoin
          predicates:
            - Path=/api/v1/**
#security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8088 
key_token: Xx4K0hF3Qp5Lp3WvF+N+4kSzCvT9uXhQ/VlIhxAs+G4=
