server:
  port: 8088

spring:
  application:
    name: ms-authentication
  data:
    mongodb:
      uri: mongodb://localhost:27017/authbd
      
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-eureka-server:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      
key_encriptacion: BOOTCAMO592025jd
key_token: Xx4K0hF3Qp5Lp3WvF+N+4kSzCvT9uXhQ/VlIhxAs+G4=
jwt_token_duration_segundos: 3600000
jwt_refresh_token_duration_segundos: 3900
