server:
  port: 8087

spring:
  application:
    name: ms-bootcoin
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankdb
      
logging:
  level:
    root: INFO  

eureka:
  client:
    serviceUrl:
      #defaultZone: http://ms-eureka-server:8761/eureka
      defaultZone: http://localhost:8761/eureka
