server:
  port: 8081

spring:
  application:
    name: ms-customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/custmersdb 
logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-eureka-server:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      
key_token: Xx4K0hF3Qp5Lp3WvF+N+4kSzCvT9uXhQ/VlIhxAs+G4=
